### PR TITLE
Refactor prepare read

### PR DESCRIPTION
**Pull request by erikkemperman**
Ref. https://github.com/erikkemperman/vinyl-prepare/commit/3558db36478500d5508431b751947d7444003d8a#commitcomment-21860733

Edit: note I have not had time to add tests, and probably won't for a week or so at least. For what it's worth though, the tests in vinyl-fs all pass with https://github.com/gulpjs/vinyl-fs/pull/229 linked to this branch of vinyl-prepare.

Hope this helps...

### CODE REVIEW

**Comment by erikkemperman** [comment]
@phated I've found a little more time and spent it upgrading the vinyl dependency to align with the one in vinyl-fs. Would you like me to tack that onto this PR or keep it separate?

**Comment by phated** [comment]
Separate please.

**Comment by phated** [comment]
Many thanks!

**Comment by erikkemperman** [comment]
Thanks for review and merge!

**Pull request merged**
