### PR TITLE
No need for options merging, remove originalSymLink hack

### PR DESCRIPTION
**Pull request by erikkemperman**

### CODE REVIEW

**Comment by erikkemperman** [comment]
Sorry, added a commit onto this, now depends on https://github.com/gulpjs/vinyl-fs/pull/236.

**Comment by phated** [comment]
@erikkemperman I think I'll cherry-pick the first commit while we discuss the other stuff between the 2 projects.

**Comment by phated** [comment]
Cherry-pick'd.  This will need a rebase for further discussion.

**Comment by phated** [comment]
I cherry-pick'd the other commit too and published.

**Comment by erikkemperman** [comment]
Sorry, missed that one request for rebase. Thanks for going ahead!

**Pull request closed without merging**
